In [8]:
import tensorflow as tf
sess = tf.InteractiveSession()
t_matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t_array = tf.constant([1, 2, 3, 4, 9, 8, 6, 5])
t_array2 = tf.constant([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# slice a part
tf.slice(t_matrix, [1, 1], [2, 2]).eval()

array([[5, 6],
       [8, 9]], dtype=int32)

In [12]:
# split the tensor
tf.split(axis = 0, num_or_size_splits = 2, value=t_array)

[<tf.Tensor 'split_2:0' shape=(4,) dtype=int32>,
 <tf.Tensor 'split_2:1' shape=(4,) dtype=int32>]

In [16]:
# tile of similar values
tf.tile([1, 2], [3]).eval()

array([1, 2, 1, 2, 1, 2], dtype=int32)

In [17]:
# [[1, 2], [3, 4]]
#  1
#3  4
#  2
tf.pad(t_matrix, [[0, 1], [2, 1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [18]:
tf.concat(axis=0, values=[t_array, t_array2]).eval()

array([1, 2, 3, 4, 9, 8, 6, 5, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [19]:
tf.stack([t_array, t_array2]).eval()

array([[1, 2, 3, 4, 9, 8, 6, 5],
       [2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [20]:
tf.reverse(t_matrix, [False, True]).eval()

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]], dtype=int32)