In [5]:
import tensorflow as tf
sess = tf.Session()
x = tf.constant([[2, 5, 3, -5], [0, 3, -2, 5], [4, 3, 5, 3], [6, 1, 4, 0]])
listx = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
listy = tf.constant([4, 5, 8, 9])
boolx = tf.constant([[True, False], [False, True]])
# this returns the index of the min of the row
tf.argmin(x, 1).eval()

array([3, 2, 1, 3])

In [7]:
# this returns the index of the max of the row
tf.argmax(x, 1).eval()

array([1, 3, 2, 0])

In [8]:
tf.where(boolx).eval()

array([[0, 0],
       [1, 1]])