In [7]:
import tensorflow as tf
s = tf.InteractiveSession()

In [16]:
a = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
b = tf.constant([[17, 18, 19, 20, 21], [22, 23, 24, 25, 26], [27, 28, 29, 30, 31], [32, 33, 34, 35, 36]])
c = tf.constant([[2., 4.], [8., 10.]])
tf.transpose(a).eval()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]], dtype=int32)

In [17]:
tf.matrix_inverse(c).eval()

array([[-0.8333334 ,  0.33333334],
       [ 0.6666667 , -0.16666667]], dtype=float32)

In [20]:
tf.matrix_determinant(c).eval()

-12.0

In [22]:
tf.matmul(a, b).eval()

array([[ 270,  280,  290,  300,  310],
       [ 662,  688,  714,  740,  766],
       [1054, 1096, 1138, 1180, 1222],
       [1446, 1504, 1562, 1620, 1678]], dtype=int32)

In [24]:
tf.matrix_solve(c, [[1], [1]]).eval()

array([[-0.5],
       [ 0.5]], dtype=float32)