In [3]:
import tensorflow as tf
sess = tf.InteractiveSession()
seg_ids =  tf.constant([0, 1, 1, 2, 2]); # group indexes : 1|1, 2| 3, 4
tens1 = tf.constant([[2, 5, 3, -5], [0, 3, -2, 5], [4, 3, 5, 3], [6, 1, 4, 0], [6, 1, 4, 0]]) # A sample constant matrix
# segments them into sums
tf.segment_sum(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]], dtype=int32)

In [4]:
# segment them in products
tf.segment_prod(tens1, seg_ids).eval()

array([[  2,   5,   3,  -5],
       [  0,   9, -10,  15],
       [ 36,   1,  16,   0]], dtype=int32)

In [5]:
# segment them in minimum of *
tf.segment_min(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [6]:
# segment them in maxmium of *
tf.segment_max(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  3,  5,  5],
       [ 6,  1,  4,  0]], dtype=int32)

In [8]:
# segment them into thier means
tf.segment_mean(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]], dtype=int32)