In [4]:
import tensorflow as tf
sess = tf.Session()
x = tf.constant([[2, 5, 3, -5], [0, 3, -2, 5], [6, 1, 4, 0]])
# actual shape of the tensor ([rows, cols])
tf.shape(x).eval() #shape of the tensor

array([3, 4], dtype=int32)

In [5]:
# to get the size rows+cols
tf.size(x).eval()

12

In [6]:
# rank of the tensor
tf.rank(x).eval()

2

In [8]:
# to resize the tensor 
# row1+col1 = row2+col2
tf.reshape(x, [6, 2]).eval()

array([[ 2,  5],
       [ 3, -5],
       [ 0,  3],
       [-2,  5],
       [ 6,  1],
       [ 4,  0]], dtype=int32)

In [10]:
# to squeeze the tensor
tf.squeeze(x).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  5],
       [ 6,  1,  4,  0]], dtype=int32)

In [11]:
# to expand the dimensions
tf.expand_dims(x, 1).eval()

array([[[ 2,  5,  3, -5]],

       [[ 0,  3, -2,  5]],

       [[ 6,  1,  4,  0]]], dtype=int32)