In [18]:
import tensorflow as tf
sess = tf.Session()
x = tf.constant([[1, 2, 3], [3, 2, 1], [-1, -2, -3]])
boolean_tensor = tf.constant([[True, False, True], [False, False, True], [True, False, False]])

In [13]:
tf.reduce_prod(x, reduction_indices = 1).eval()

array([ 6,  6, -6], dtype=int32)

In [15]:
tf.reduce_min(x, reduction_indices = 1).eval()

array([ 1,  1, -3], dtype=int32)

In [16]:
tf.reduce_mean(x, reduction_indices = 1).eval()

array([ 2,  2, -2], dtype=int32)

In [19]:
tf.reduce_all(boolean_tensor, reduction_indices = 1).eval()

array([False, False, False])

In [25]:
tf.reduce_any(boolean_tensor, reduction_indices = 1).eval()

array([ True,  True,  True])